# Generated by Django 6.0.5 on 2026-05-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoIcerik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('ozet', 'Özet (Short Description)'), ('detay', 'Detay Açıklama (Description)'), ('meta_baslik', 'Meta Başlık (Meta Title)'), ('meta_aciklama', 'Meta Açıklama (Meta Desc)'), ('anahtar_kelime', 'Anahtar Kelimeler')], max_length=30, verbose_name='İçerik Tipi')),
                ('icerik', models.TextField(verbose_name='İçerik (HTML)')),
                ('kaynak', models.CharField(choices=[('ai', 'Claude AI'), ('sablon', 'Şablon'), ('manuel', 'Manuel')], default='ai', max_length=10, verbose_name='Kaynak')),
                ('model_adi', models.CharField(blank=True, max_length=100, verbose_name='AI Model')),
                ('onaylandi', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_icerikleri', to='urun.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'SEO İçerik',
                'verbose_name_plural': 'SEO İçerikler',
                'ordering': ['-created_at'],
            },
        ),
    ]
