# Generated by Django 6.0.5 on 2026-05-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('ust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kategoriler', to='urun.kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=200, unique=True, verbose_name='Ürün Kodu')),
                ('marka', models.CharField(blank=True, max_length=200, verbose_name='Marka')),
                ('ad', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('tedarikci_kodu', models.CharField(blank=True, max_length=200, verbose_name='Tedarikçi Kodu')),
                ('barkod', models.CharField(blank=True, max_length=50, verbose_name='Barkod (EAN)')),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fiyat')),
                ('ham_aciklama', models.TextField(blank=True, help_text='Tedarikçiden gelen, düzenlenmemiş açıklama', verbose_name='Ham Açıklama')),
                ('teknik_ozellik', models.TextField(blank=True, help_text='Madde madde veya serbest metin', verbose_name='Teknik Özellikler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urun.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-created_at'],
            },
        ),
    ]
