# Generated by Django 6.0.5 on 2026-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='kaynak_url',
            field=models.URLField(blank=True, help_text='Ürünün bulunduğu web sayfası — içerik buradan çekilir', max_length=2000, verbose_name='Kaynak URL'),
        ),
    ]
